#!/bin/bash

find /autograder/submission -name '*.asm' -exec cp {} /autograder/source/ \;
cp -r /autograder/grader/tests/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any out files in submission
rm -f *.out

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
